# Install script for directory: /home/nguyen/Workspace/micmac-webassembly/src/CBinaires

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/mm3d.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/mm3d.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/mm3d.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/mm3d.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/mm3d.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/AperiCloud.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/AperiCloud.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/AperiCloud.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/AperiCloud.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/AperiCloud.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/Digeo.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/Digeo.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Digeo.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Digeo.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Digeo.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/Apero.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/Apero.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Apero.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Apero.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Apero.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/Apero2PMVS.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/Apero2PMVS.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Apero2PMVS.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Apero2PMVS.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Apero2PMVS.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/mmxv.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/mmxv.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/mmxv.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/mmxv.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/mmxv.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/Bascule.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/Bascule.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Bascule.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Bascule.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Bascule.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/BatchFDC.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/BatchFDC.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/BatchFDC.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/BatchFDC.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/BatchFDC.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/CmpCalib.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/CmpCalib.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/CmpCalib.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/CmpCalib.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/CmpCalib.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/Dequant.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/Dequant.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Dequant.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Dequant.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Dequant.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/vic.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/vic.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/vic.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/vic.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/vic.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/Devlop.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/Devlop.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Devlop.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Devlop.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Devlop.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/Drunk.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/Drunk.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Drunk.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Drunk.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Drunk.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/ElDcraw.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/ElDcraw.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/ElDcraw.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/ElDcraw.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/ElDcraw.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/GCPBascule.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/GCPBascule.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/GCPBascule.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/GCPBascule.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/GCPBascule.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/CenterBascule.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/CenterBascule.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/CenterBascule.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/CenterBascule.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/CenterBascule.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/GIMMI.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/GIMMI.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/GIMMI.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/GIMMI.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/GIMMI.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/GenXML2Cpp.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/GenXML2Cpp.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/GenXML2Cpp.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/GenXML2Cpp.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/GenXML2Cpp.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/Gri2Bin.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/Gri2Bin.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Gri2Bin.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Gri2Bin.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Gri2Bin.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/GrShade.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/GrShade.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/GrShade.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/GrShade.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/GrShade.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/MakeGrid.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/MakeGrid.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/MakeGrid.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/MakeGrid.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/MakeGrid.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/Malt.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/Malt.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Malt.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Malt.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Malt.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/MapCmd.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/MapCmd.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/MapCmd.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/MapCmd.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/MapCmd.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/MICMAC.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/MICMAC.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/MICMAC.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/MICMAC.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/MICMAC.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/MpDcraw.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/MpDcraw.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/MpDcraw.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/MpDcraw.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/MpDcraw.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/Nuage2Ply.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/Nuage2Ply.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Nuage2Ply.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Nuage2Ply.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Nuage2Ply.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/Pasta.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/Pasta.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Pasta.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Pasta.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Pasta.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/PastDevlop.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/PastDevlop.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/PastDevlop.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/PastDevlop.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/PastDevlop.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/Pastis.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/Pastis.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Pastis.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Pastis.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Pastis.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/Porto.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/Porto.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Porto.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Porto.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Porto.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/Reduc2MM.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/Reduc2MM.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Reduc2MM.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Reduc2MM.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Reduc2MM.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/ReducHom.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/ReducHom.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/ReducHom.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/ReducHom.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/ReducHom.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/RepLocBascule.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/RepLocBascule.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/RepLocBascule.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/RepLocBascule.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/RepLocBascule.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/SBGlobBascule.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/SBGlobBascule.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/SBGlobBascule.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/SBGlobBascule.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/SBGlobBascule.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/ScaleIm.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/ScaleIm.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/ScaleIm.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/ScaleIm.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/ScaleIm.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/ScaleNuage.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/ScaleNuage.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/ScaleNuage.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/ScaleNuage.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/ScaleNuage.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/SysCoordPolyn.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/SysCoordPolyn.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/SysCoordPolyn.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/SysCoordPolyn.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/SysCoordPolyn.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/Tapas.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/Tapas.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Tapas.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Tapas.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Tapas.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/Campari.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/Campari.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Campari.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Campari.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Campari.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/Tapioca.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/Tapioca.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Tapioca.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Tapioca.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Tapioca.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/Tarama.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/Tarama.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Tarama.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Tarama.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Tarama.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/Tawny.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/Tawny.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Tawny.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Tawny.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Tawny.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/TestCam.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/TestCam.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/TestCam.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/TestCam.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/TestCam.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/TestCmds.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/TestCmds.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/TestCmds.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/TestCmds.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/TestCmds.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/tiff_info.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/tiff_info.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/tiff_info.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/tiff_info.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/tiff_info.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/to8Bits.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/to8Bits.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/to8Bits.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/to8Bits.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/to8Bits.js")
    endif()
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/nguyen/Workspace/micmac-webassembly/bin/Vino.js")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/home/nguyen/Workspace/micmac-webassembly/bin" TYPE EXECUTABLE FILES "/home/nguyen/Workspace/micmac-webassembly/build/src/CBinaires/Vino.js")
  if(EXISTS "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Vino.js" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Vino.js")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/home/nguyen/Workspace/micmac-webassembly/bin/Vino.js")
    endif()
  endif()
endif()

